/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MeetRoomRouteImport } from './routes/meet.$room'
import { Route as ApiOrbitTranslationTokenRouteImport } from './routes/api.orbit-translation-token'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MeetRoomRoute = MeetRoomRouteImport.update({
  id: '/meet/$room',
  path: '/meet/$room',
  getParentRoute: () => rootRouteImport,
} as any)

const ApiOrbitTranslationTokenRoute = ApiOrbitTranslationTokenRouteImport.update({
  id: '/api/orbit-translation-token',
  path: '/api/orbit-translation-token',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/meet/$room': typeof MeetRoomRoute
  '/api/orbit-translation-token': typeof ApiOrbitTranslationTokenRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/meet/$room': typeof MeetRoomRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/meet/$room': typeof MeetRoomRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/meet/$room' | '/api/orbit-translation-token'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/meet/$room' | '/api/orbit-translation-token'
  id: '__root__' | '/' | '/meet/$room' | '/api/orbit-translation-token'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  MeetRoomRoute: typeof MeetRoomRoute
  ApiOrbitTranslationTokenRoute: typeof ApiOrbitTranslationTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/meet/$room': {
      id: '/meet/$room'
      path: '/meet/$room'
      fullPath: '/meet/$room'
      preLoaderRoute: typeof MeetRoomRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/orbit-translation-token': {
      id: '/api/orbit-translation-token'
      path: '/api/orbit-translation-token'
      fullPath: '/api/orbit-translation-token'
      preLoaderRoute: typeof ApiOrbitTranslationTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  MeetRoomRoute: MeetRoomRoute,
  ApiOrbitTranslationTokenRoute: ApiOrbitTranslationTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
